stages:
  run_pipeline:
    cmd: python pipeline.py
    deps:
    - data/input_data
    - data/output_data
    - pipeline.py
    metrics:
    - data/artifacts/metrics.json:
        cache: false
    plots:
    - data/artifacts/confusion_matrix.png
