stages:
  run_pipeline:
    cmd: python pipeline.py
    deps:
    - data
    - pipeline.py
    metrics:
    - artifacts/metrics.json:
        cache: false
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  model:
    path: artifacts/model.pkl
    type: model
